
spring:
  cassandra:
    contactPoints: localhost
    username: admin
    password: admin
    local-datacenter: datacenter1
    keyspace-name: test
    port: 9042
#  data:
#    cassandra:
#      keyspace-name: test
#      port: 9042
  servlet:
    multipart:
      max-file-size: 10MB  # Set your desired file size limit
      max-request-size: 10MB  # Set your desired request size limit
upload:
    file:
      maxSize: 10485760
# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#  config:
#    import: configserver:${config-server-url}
#  cloud:
#    bus:
#      enabled: true
#      refresh:
#        enabled: true


cassandra:
  migration:
    keyspaceName: test
    tablePrefix: t



